In [3]:
import pandas as pd
import os

In [47]:
def load_raw_data(filepath):
    """
    Load the raw CSV dataset from disk.
    """
    filepath = os.path.join("data", "GlobalWeatherRepository.csv")
    df = pd.read_csv(filepath)
    return df

In [48]:
filepath = "data/GlobalWeatherRepository.csv"
df = load_raw_data(filepath)
df_original = df.copy()
df.head()

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1715849100,2024-05-16 13:15,26.6,79.8,Partly Cloudy,...,8.4,26.6,1,1,04:50 AM,06:50 PM,12:12 PM,01:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,1715849100,2024-05-16 10:45,19.0,66.2,Partly cloudy,...,1.1,2.0,1,1,05:21 AM,07:54 PM,12:58 PM,02:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,1715849100,2024-05-16 09:45,23.0,73.4,Sunny,...,10.4,18.4,1,1,05:40 AM,07:50 PM,01:15 PM,02:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1715849100,2024-05-16 10:45,6.3,43.3,Light drizzle,...,0.7,0.9,1,1,06:31 AM,09:11 PM,02:12 PM,03:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,1715849100,2024-05-16 09:45,26.0,78.8,Partly cloudy,...,183.4,262.3,5,10,06:12 AM,05:55 PM,01:17 PM,12:38 AM,Waxing Gibbous,55

In [49]:
def standardize_columns(df):
    """
    Standardize column names:
    - Remove leading/trailing spaces
    - Convert to lowercase
    - Replace spaces and hyphens with underscores

    This ensures consistency when referencing columns later.
    """
    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_", regex=False)
        .str.replace("-", "_", regex=False)
    )
    return df

In [50]:
df = standardize_columns(df)
df.head()

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_pm2.5,air_quality_pm10,air_quality_us_epa_index,air_quality_gb_defra_index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1715849100,2024-05-16 13:15,26.6,79.8,Partly Cloudy,...,8.4,26.6,1,1,04:50 AM,06:50 PM,12:12 PM,01:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,1715849100,2024-05-16 10:45,19.0,66.2,Partly cloudy,...,1.1,2.0,1,1,05:21 AM,07:54 PM,12:58 PM,02:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,1715849100,2024-05-16 09:45,23.0,73.4,Sunny,...,10.4,18.4,1,1,05:40 AM,07:50 PM,01:15 PM,02:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1715849100,2024-05-16 10:45,6.3,43.3,Light drizzle,...,0.7,0.9,1,1,06:31 AM,09:11 PM,02:12 PM,03:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,1715849100,2024-05-16 09:45,26.0,78.8,Partly cloudy,...,183.4,262.3,5,10,06:12 AM,05:55 PM,01:17 PM,12:38 AM,Waxing Gibbous,55

In [51]:
def parse_datetime_local(df, datetime_col="last_updated"):
    """
    Convert the 'last_updated' column to datetime format.
    """
    df[datetime_col] = pd.to_datetime(df[datetime_col], errors="coerce")

    # Drop rows where datetime conversion failed
    df = df.dropna(subset=[datetime_col])

    return df

def parse_datetime_unix(df, datetime_col="last_updated_epoch"):
    """
    Convert Unix epoch timestamp (seconds) into UTC datetime.
    """
    # Convert epoch (seconds) → UTC datetime
    df[datetime_col] = pd.to_datetime(df[datetime_col], unit="s", utc=True)

    return df

In [53]:
df = parse_datetime_local(df)
df.head()

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_pm2.5,air_quality_pm10,air_quality_us_epa_index,air_quality_gb_defra_index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1715849100,2024-05-16 13:15:00,26.6,79.8,Partly Cloudy,...,8.4,26.6,1,1,04:50 AM,06:50 PM,12:12 PM,01:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,1715849100,2024-05-16 10:45:00,19.0,66.2,Partly cloudy,...,1.1,2.0,1,1,05:21 AM,07:54 PM,12:58 PM,02:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,73.4,Sunny,...,10.4,18.4,1,1,05:40 AM,07:50 PM,01:15 PM,02:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1715849100,2024-05-16 10:45:00,6.3,43.3,Light drizzle,...,0.7,0.9,1,1,06:31 AM,09:11 PM,02:12 PM,03:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,78.8,Partly cloudy,...,183.4,262.3,5,10,06:12 AM,05:55 PM,01:17 PM,12:38 AM,Waxing Gibbous,55

In [54]:
df = parse_datetime_unix(df)
df.head()

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_pm2.5,air_quality_pm10,air_quality_us_epa_index,air_quality_gb_defra_index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,2024-05-16 08:45:00+00:00,2024-05-16 13:15:00,26.6,79.8,Partly Cloudy,...,8.4,26.6,1,1,04:50 AM,06:50 PM,12:12 PM,01:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,2024-05-16 08:45:00+00:00,2024-05-16 10:45:00,19.0,66.2,Partly cloudy,...,1.1,2.0,1,1,05:21 AM,07:54 PM,12:58 PM,02:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,2024-05-16 08:45:00+00:00,2024-05-16 09:45:00,23.0,73.4,Sunny,...,10.4,18.4,1,1,05:40 AM,07:50 PM,01:15 PM,02:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,2024-05-16 08:45:00+00:00,2024-05-16 10:45:00,6.3,43.3,Light drizzle,...,0.7,0.9,1,1,06:31 AM,09:11 PM,02:12 PM,03:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,2024-05-16 08:45:00+00:00,2024-05-16 09:45:00,26.0,78.8,Partly cloudy,...,183.4,262.3,5,10,06:12 AM,05:55 PM,01:17 PM,12:38 AM,Waxing Gibbous,55

In [55]:
def drop_duplicates(df):
    """
    Remove duplicate rows.
    """
    return df.drop_duplicates().reset_index(drop=True)

In [56]:
df = drop_duplicates(df)
df.head()

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_pm2.5,air_quality_pm10,air_quality_us_epa_index,air_quality_gb_defra_index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,2024-05-16 08:45:00+00:00,2024-05-16 13:15:00,26.6,79.8,Partly Cloudy,...,8.4,26.6,1,1,04:50 AM,06:50 PM,12:12 PM,01:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,2024-05-16 08:45:00+00:00,2024-05-16 10:45:00,19.0,66.2,Partly cloudy,...,1.1,2.0,1,1,05:21 AM,07:54 PM,12:58 PM,02:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,2024-05-16 08:45:00+00:00,2024-05-16 09:45:00,23.0,73.4,Sunny,...,10.4,18.4,1,1,05:40 AM,07:50 PM,01:15 PM,02:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,2024-05-16 08:45:00+00:00,2024-05-16 10:45:00,6.3,43.3,Light drizzle,...,0.7,0.9,1,1,06:31 AM,09:11 PM,02:12 PM,03:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,2024-05-16 08:45:00+00:00,2024-05-16 09:45:00,26.0,78.8,Partly cloudy,...,183.4,262.3,5,10,06:12 AM,05:55 PM,01:17 PM,12:38 AM,Waxing Gibbous,55

In [57]:
def create_timeseries_index(df, city_col="location_name", country_col="country", datetime_col="last_updated_epoch"):
    """
    Create a proper time-series multi-index:
    (city, country, datetime)
    """

    required_cols = [city_col, datetime_col]
    for col in required_cols:
        if col not in df.columns:
            raise ValueError(f"Required column '{col}' not found.")

    if country_col in df.columns:
        df = df.set_index([city_col, country_col, datetime_col])
    else:
        df = df.set_index([city_col, datetime_col])

    df = df.sort_index()

    return df

In [58]:
df = create_timeseries_index(df)
df.head()

                                                     latitude  longitude  \
location_name     country last_updated_epoch
'S Gravenjansdijk Belgium 2024-05-31 14:15:00+00:00     51.25       3.63
                          2024-06-01 14:30:00+00:00     51.25       3.63
                          2024-06-04 14:15:00+00:00     51.25       3.63
                          2024-06-05 14:15:00+00:00     51.25       3.63
                          2024-06-11 14:15:00+00:00     51.25       3.63

                                                            timezone  \
location_name     country last_updated_epoch
'S Gravenjansdijk Belgium 2024-05-31 14:15:00+00:00  Europe/Brussels
                          2024-06-01 14:30:00+00:00  Europe/Brussels
                          2024-06-04 14:15:00+00:00  Europe/Brussels
                          2024-06-05 14:15:00+00:00  Europe/Brussels
                          2024-06-11 14:15:00+00:00  Europe/Brussels

                                                           last_updated  \
location_name     country last_updated_epoch
'S Gravenjansdijk Belgium 2024-05-31 14:15:00+00:00 2024-05-31 16:15:00
                          2024-06-01 14:30:00+00:00 2024-06-01 16:30:00
                          2024-06-04 14:15:00+00:00 2024-06-04 16:15:00
                          2024-06-05 14:15:00+00:00 2024-06-05 16:15:00
                          2024-06-11 14:15:00+00:00 2024-06-11 16:15:00

                                                     temperature_celsius  \
location_name     country last_updated_epoch
'S Gravenjansdijk Belgium 2024-05-31 14:15:00+00:00                 16.0
                          2024-06-01 14:30:00+00:00                 16.0
                          2024-06-04 14:15:00+00:00                 18.0
                          2024-06-05 14:15:00+00:00                 15.0
                          2024-06-11 14:15:00+00:00                 15.2

                                                     temperature_fahrenheit  \
location_name     country last_updated_epoch
'S Gravenjansdijk Belgium 2024-05-31 14:15:00+00:00                    60.8
                          2024-06-01 14:30:00+00:00                    60.8
                          2024-06-04 14:15:00+00:00                    64.4
                          2024-06-05 14:15:00+00:00                    59.0
                          2024-06-11 14:15:00+00:00                    59.4

                                                    condition_text  wind_mph  \
location_name     country last_updated_epoch
'S Gravenjansdijk Belgium 2024-05-31 14:15:00+00:00  Moderate rain      17.4
                          2024-06-01 14:30:00+00:00       Overcast       9.4
                          2024-06-04 14:15:00+00:00  Partly cloudy      16.1
                          2024-06-05 14:15:00+00:00  Partly cloudy       6.9
                          2024-06-11 14:15:00+00:00  Partly cloudy      15.0

                                                     wind_kph  wind_degree  \
location_name     country last_updated_epoch
'S Gravenjansdijk Belgium 2024-05-31 14:15:00+00:00      28.1           20
                          2024-06-01 14:30:00+00:00      15.1          330
                          2024-06-04 14:15:00+00:00      25.9          270
                          2024-06-05 14:15:00+00:00      11.2          330
                          2024-06-11 14:15:00+00:00      24.1          280

                                                     ... air_quality_pm2.5  \
location_name     country last_updated_epoch         ...
'S Gravenjansdijk Belgium 2024-05-31 14:15:00+00:00  ...               2.2
                          2024-06-01 14:30:00+00:00  ...               6.5
                          2024-06-04 14:15:00+00:00  ...               5.7
                          2024-06-05 14:15:00+00:00  ...               1.2
                          2024-06-11 14:15:00+00:00  ...               0.5

                                                     air_quality_pm10  \
location_name     country last_updated_epoch
'S Gravenjansdijk Belgium 2024-05-31 14:15:00+00:00               3.4
                          2024-06-01 14:30:00+00:00              19.6
                          2024-06-04 14:15:00+00:00               6.0
                          2024-06-05 14:15:00+00:00               2.4
                          2024-06-11 14:15:00+00:00               0.9

                                                     air_quality_us_epa_index  \
location_name     country last_updated_epoch
'S Gravenjansdijk Belgium 2024-05-31 14:15:00+00:00                         1
                          2024-06-01 14:30:00+00:00                         1
                          2024-06-04 14:15:00+00:00                         1
                          2024-06-05 14:15:00+00:00                         1
                          2024-06-11 14:15:00+00:00                         1

                                                     air_quality_gb_defra_index  \
location_name     country last_updated_epoch
'S Gravenjansdijk Belgium 2024-05-31 14:15:00+00:00                           1
                          2024-06-01 14:30:00+00:00                           1
                          2024-06-04 14:15:00+00:00                           1
                          2024-06-05 14:15:00+00:00                           1
                          2024-06-11 14:15:00+00:00                           1

                                                      sunrise    sunset  \
location_name     country last_updated_epoch
'S Gravenjansdijk Belgium 2024-05-31 14:15:00+00:00  05:36 AM  09:52 PM
                          2024-06-01 14:30:00+00:00  05:35 AM  09:53 PM
                          2024-06-04 14:15:00+00:00  05:33 AM  09:56 PM
                          2024-06-05 14:15:00+00:00  05:33 AM  09:56 PM
                          2024-06-11 14:15:00+00:00  05:30 AM  10:01 PM

                                                     moonrise   moonset  \
location_name     country last_updated_epoch
'S Gravenjansdijk Belgium 2024-05-31 14:15:00+00:00  02:59 AM  02:09 PM
                          2024-06-01 14:30:00+00:00  03:12 AM  03:34 PM
                          2024-06-04 14:15:00+00:00  03:56 AM  07:57 PM
                          2024-06-05 14:15:00+00:00  04:17 AM  09:25 PM
                          2024-06-11 14:15:00+00:00  10:16 AM  01:31 AM

                                                          moon_phase  \
location_name     country last_updated_epoch
'S Gravenjansdijk Belgium 2024-05-31 14:15:00+00:00  Waning Crescent
                          2024-06-01 14:30:00+00:00  Waning Crescent
                          2024-06-04 14:15:00+00:00  Waning Crescent
                          2024-06-05 14:15:00+00:00  Waning Crescent
                          2024-06-11 14:15:00+00:00  Waxing Crescent

                                                     moon_illumination
location_name     country last_updated_epoch
'S Gravenjansdijk Belgium 2024-05-31 14:15:00+00:00                 47
                          2024-06-01 14:30:00+00:00                 35
                          2024-06-04 14:15:00+00:00                  8
                          2024-06-05 14:15:00+00:00                  3
                          2024-06-11 14:15:00+00:00                 21

[5 rows x 38 columns]

In [59]:
df[:10]

                                                     latitude  longitude  \
location_name     country last_updated_epoch
'S Gravenjansdijk Belgium 2024-05-31 14:15:00+00:00     51.25       3.63
                          2024-06-01 14:30:00+00:00     51.25       3.63
                          2024-06-04 14:15:00+00:00     51.25       3.63
                          2024-06-05 14:15:00+00:00     51.25       3.63
                          2024-06-11 14:15:00+00:00     51.25       3.63
                          2024-06-14 14:00:00+00:00     51.25       3.63
                          2024-06-15 14:00:00+00:00     51.25       3.63
                          2024-06-16 13:45:00+00:00     51.25       3.63
                          2024-06-20 13:45:00+00:00     51.25       3.63
                          2024-06-21 13:45:00+00:00     51.25       3.63

                                                            timezone  \
location_name     country last_updated_epoch
'S Gravenjansdijk Belgium 2024-05-31 14:15:00+00:00  Europe/Brussels
                          2024-06-01 14:30:00+00:00  Europe/Brussels
                          2024-06-04 14:15:00+00:00  Europe/Brussels
                          2024-06-05 14:15:00+00:00  Europe/Brussels
                          2024-06-11 14:15:00+00:00  Europe/Brussels
                          2024-06-14 14:00:00+00:00  Europe/Brussels
                          2024-06-15 14:00:00+00:00  Europe/Brussels
                          2024-06-16 13:45:00+00:00  Europe/Brussels
                          2024-06-20 13:45:00+00:00  Europe/Brussels
                          2024-06-21 13:45:00+00:00  Europe/Brussels

                                                           last_updated  \
location_name     country last_updated_epoch
'S Gravenjansdijk Belgium 2024-05-31 14:15:00+00:00 2024-05-31 16:15:00
                          2024-06-01 14:30:00+00:00 2024-06-01 16:30:00
                          2024-06-04 14:15:00+00:00 2024-06-04 16:15:00
                          2024-06-05 14:15:00+00:00 2024-06-05 16:15:00
                          2024-06-11 14:15:00+00:00 2024-06-11 16:15:00
                          2024-06-14 14:00:00+00:00 2024-06-14 16:00:00
                          2024-06-15 14:00:00+00:00 2024-06-15 16:00:00
                          2024-06-16 13:45:00+00:00 2024-06-16 15:45:00
                          2024-06-20 13:45:00+00:00 2024-06-20 15:45:00
                          2024-06-21 13:45:00+00:00 2024-06-21 15:45:00

                                                     temperature_celsius  \
location_name     country last_updated_epoch
'S Gravenjansdijk Belgium 2024-05-31 14:15:00+00:00                 16.0
                          2024-06-01 14:30:00+00:00                 16.0
                          2024-06-04 14:15:00+00:00                 18.0
                          2024-06-05 14:15:00+00:00                 15.0
                          2024-06-11 14:15:00+00:00                 15.2
                          2024-06-14 14:00:00+00:00                 16.5
                          2024-06-15 14:00:00+00:00                 17.4
                          2024-06-16 13:45:00+00:00                 16.1
                          2024-06-20 13:45:00+00:00                 21.3
                          2024-06-21 13:45:00+00:00                 16.4

                                                     temperature_fahrenheit  \
location_name     country last_updated_epoch
'S Gravenjansdijk Belgium 2024-05-31 14:15:00+00:00                    60.8
                          2024-06-01 14:30:00+00:00                    60.8
                          2024-06-04 14:15:00+00:00                    64.4
                          2024-06-05 14:15:00+00:00                    59.0
                          2024-06-11 14:15:00+00:00                    59.4
                          2024-06-14 14:00:00+00:00                    61.6
                          2024-06-15 14:00:00+00:00                    63.3
                          2024-06-16 13:45:00+00:00                    61.0
                          2024-06-20 13:45:00+00:00                    70.3
                          2024-06-21 13:45:00+00:00                    61.5

                                                                    condition_text  \
location_name     country last_updated_epoch
'S Gravenjansdijk Belgium 2024-05-31 14:15:00+00:00                  Moderate rain
                          2024-06-01 14:30:00+00:00                       Overcast
                          2024-06-04 14:15:00+00:00                  Partly cloudy
                          2024-06-05 14:15:00+00:00                  Partly cloudy
                          2024-06-11 14:15:00+00:00                  Partly cloudy
                          2024-06-14 14:00:00+00:00              Light rain shower
                          2024-06-15 14:00:00+00:00                       Overcast
                          2024-06-16 13:45:00+00:00                  Moderate rain
                          2024-06-20 13:45:00+00:00                  Partly cloudy
                          2024-06-21 13:45:00+00:00  Moderate or heavy rain shower

                                                     wind_mph  wind_kph  \
location_name     country last_updated_epoch
'S Gravenjansdijk Belgium 2024-05-31 14:15:00+00:00      17.4      28.1
                          2024-06-01 14:30:00+00:00       9.4      15.1
                          2024-06-04 14:15:00+00:00      16.1      25.9
                          2024-06-05 14:15:00+00:00       6.9      11.2
                          2024-06-11 14:15:00+00:00      15.0      24.1
                          2024-06-14 14:00:00+00:00      13.0      20.9
                          2024-06-15 14:00:00+00:00      13.6      22.0
                          2024-06-16 13:45:00+00:00      13.6      22.0
                          2024-06-20 13:45:00+00:00      11.9      19.1
                          2024-06-21 13:45:00+00:00       5.6       9.0

                                                     wind_degree  ...  \
location_name     country last_updated_epoch                      ...
'S Gravenjansdijk Belgium 2024-05-31 14:15:00+00:00           20  ...
                          2024-06-01 14:30:00+00:00          330  ...
                          2024-06-04 14:15:00+00:00          270  ...
                          2024-06-05 14:15:00+00:00          330  ...
                          2024-06-11 14:15:00+00:00          280  ...
                          2024-06-14 14:00:00+00:00          222  ...
                          2024-06-15 14:00:00+00:00          210  ...
                          2024-06-16 13:45:00+00:00          220  ...
                          2024-06-20 13:45:00+00:00           50  ...
                          2024-06-21 13:45:00+00:00          330  ...

                                                    air_quality_pm2.5  \
location_name     country last_updated_epoch
'S Gravenjansdijk Belgium 2024-05-31 14:15:00+00:00               2.2
                          2024-06-01 14:30:00+00:00               6.5
                          2024-06-04 14:15:00+00:00               5.7
                          2024-06-05 14:15:00+00:00               1.2
                          2024-06-11 14:15:00+00:00               0.5
                          2024-06-14 14:00:00+00:00               1.8
                          2024-06-15 14:00:00+00:00               0.6
                          2024-06-16 13:45:00+00:00               0.5
                          2024-06-20 13:45:00+00:00               3.0
                          2024-06-21 13:45:00+00:00               5.0

                                                     air_quality_pm10  \
location_name     country last_updated_epoch
'S Gravenjansdijk Belgium 2024-05-31 14:15:00+00:00               3.4
                          2024-06-01 14:30:00+00:00              19.6
                          2024-06-04 14:15:00+00:00               6.0
                          2024-06-05 14:15:00+00:00               2.4
                          2024-06-11 14:15:00+00:00               0.9
                          2024-06-14 14:00:00+00:00               2.0
                          2024-06-15 14:00:00+00:00               0.7
                          2024-06-16 13:45:00+00:00               0.6
                          2024-06-20 13:45:00+00:00               4.5
                          2024-06-21 13:45:00+00:00               9.2

                                                     air_quality_us_epa_index  \
location_name     country last_updated_epoch
'S Gravenjansdijk Belgium 2024-05-31 14:15:00+00:00                         1
                          2024-06-01 14:30:00+00:00                         1
                          2024-06-04 14:15:00+00:00                         1
                          2024-06-05 14:15:00+00:00                         1
                          2024-06-11 14:15:00+00:00                         1
                          2024-06-14 14:00:00+00:00                         1
                          2024-06-15 14:00:00+00:00                         1
                          2024-06-16 13:45:00+00:00                         1
                          2024-06-20 13:45:00+00:00                         1
                          2024-06-21 13:45:00+00:00                         1

                                                     air_quality_gb_defra_index  \
location_name     country last_updated_epoch
'S Gravenjansdijk Belgium 2024-05-31 14:15:00+00:00                           1
                          2024-06-01 14:30:00+00:00                           1
                          2024-06-04 14:15:00+00:00                           1
                          2024-06-05 14:15:00+00:00                           1
                          2024-06-11 14:15:00+00:00                           1
                          2024-06-14 14:00:00+00:00                           1
                          2024-06-15 14:00:00+00:00                           1
                          2024-06-16 13:45:00+00:00                           1
                          2024-06-20 13:45:00+00:00                           1
                          2024-06-21 13:45:00+00:00                           1

                                                      sunrise    sunset  \
location_name     country last_updated_epoch
'S Gravenjansdijk Belgium 2024-05-31 14:15:00+00:00  05:36 AM  09:52 PM
                          2024-06-01 14:30:00+00:00  05:35 AM  09:53 PM
                          2024-06-04 14:15:00+00:00  05:33 AM  09:56 PM
                          2024-06-05 14:15:00+00:00  05:33 AM  09:56 PM
                          2024-06-11 14:15:00+00:00  05:30 AM  10:01 PM
                          2024-06-14 14:00:00+00:00  05:29 AM  10:03 PM
                          2024-06-15 14:00:00+00:00  05:29 AM  10:03 PM
                          2024-06-16 13:45:00+00:00  05:29 AM  10:04 PM
                          2024-06-20 13:45:00+00:00  05:30 AM  10:05 PM
                          2024-06-21 13:45:00+00:00  05:30 AM  10:05 PM

                                                     moonrise   moonset  \
location_name     country last_updated_epoch
'S Gravenjansdijk Belgium 2024-05-31 14:15:00+00:00  02:59 AM  02:09 PM
                          2024-06-01 14:30:00+00:00  03:12 AM  03:34 PM
                          2024-06-04 14:15:00+00:00  03:56 AM  07:57 PM
                          2024-06-05 14:15:00+00:00  04:17 AM  09:25 PM
                          2024-06-11 14:15:00+00:00  10:16 AM  01:31 AM
                          2024-06-14 14:00:00+00:00  01:52 PM  02:10 AM
                          2024-06-15 14:00:00+00:00  03:01 PM  02:20 AM
                          2024-06-16 13:45:00+00:00  04:11 PM  02:30 AM
                          2024-06-20 13:45:00+00:00  09:16 PM  03:36 AM
                          2024-06-21 13:45:00+00:00  10:26 PM  04:10 AM

                                                          moon_phase  \
location_name     country last_updated_epoch
'S Gravenjansdijk Belgium 2024-05-31 14:15:00+00:00  Waning Crescent
                          2024-06-01 14:30:00+00:00  Waning Crescent
                          2024-06-04 14:15:00+00:00  Waning Crescent
                          2024-06-05 14:15:00+00:00  Waning Crescent
                          2024-06-11 14:15:00+00:00  Waxing Crescent
                          2024-06-14 14:00:00+00:00    First Quarter
                          2024-06-15 14:00:00+00:00   Waxing Gibbous
                          2024-06-16 13:45:00+00:00   Waxing Gibbous
                          2024-06-20 13:45:00+00:00   Waxing Gibbous
                          2024-06-21 13:45:00+00:00        Full Moon

                                                     moon_illumination
location_name     country last_updated_epoch
'S Gravenjansdijk Belgium 2024-05-31 14:15:00+00:00                 47
                          2024-06-01 14:30:00+00:00                 35
                          2024-06-04 14:15:00+00:00                  8
                          2024-06-05 14:15:00+00:00                  3
                          2024-06-11 14:15:00+00:00                 21
                          2024-06-14 14:00:00+00:00                 48
                          2024-06-15 14:00:00+00:00                 57
                          2024-06-16 13:45:00+00:00                 67
                          2024-06-20 13:45:00+00:00                 95
                          2024-06-21 13:45:00+00:00                 99

[10 rows x 38 columns]

In [2]:
def load_raw_data(filepath):
    """
    Load the raw CSV dataset from disk.
    """
    filepath = os.path.join("data", "GlobalWeatherRepository.csv")
    df = pd.read_csv(filepath)
    return df


def standardize_columns(df):
    """
    Standardize column names:
    - Remove leading/trailing spaces
    - Convert to lowercase
    - Replace spaces and hyphens with underscores

    This ensures consistency when referencing columns later.
    """
    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_", regex=False)
        .str.replace("-", "_", regex=False)
    )
    return df


def parse_datetime(df, datetime_col):
    """
    Convert the 'last_updated' column to datetime format.
    """
    df[datetime_col] = pd.to_datetime(df[datetime_col], errors="coerce")

    # Drop rows where datetime conversion failed
    df = df.dropna(subset=[datetime_col])

    return df


def drop_duplicates(df):
    """
    Remove duplicate rows.
    """
    return df.drop_duplicates().reset_index(drop=True)


def create_timeseries_index(df):
    """
    Create a multi-index for proper time-series analysis.

    Index structure:
        (city, country, lastupdated)
    or
        (city, lastupdated)

    This enables grouped time-series modeling per city.
    """
    if "country" in df.columns:
        df = df.set_index(["city", "country", "lastupdated"])
    else:
        df = df.set_index(["city", "lastupdated"])

    # Sort to ensure chronological order
    df = df.sort_index()

    return df


def load_clean_data():
    """
    Complete data loading pipeline:
        1. Load raw CSV
        2. Standardize column names
        3. Parse datetime
        4. Remove duplicates
        5. Create time-series index

    Returns a clean dataframe ready for EDA and modeling.
    """
    df = load_raw_data()
    df = standardize_columns(df)
    df = parse_datetime(df)
    df = drop_duplicates(df)
    df = create_timeseries_index(df)

    return df

In [3]:
df = load_clean_data()

KeyError: 'lastupdated'